# Generated by Django 6.0.7 on 2026-07-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('total_distance_miles', models.FloatField(default=0)),
                ('total_duration_hours', models.FloatField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('stops', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('events', models.JSONField(default=list)),
                ('totals', models.JSONField(default=dict)),
                ('day_index', models.PositiveIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip')),
            ],
            options={
                'ordering': ['day_index'],
            },
        ),
    ]
