# Generated by Django 6.0.7 on 2026-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
